### ISSUE TITLE
Unspecified options in ssh_config.j2

### ISSUE THREAD

**Issue by will-maclean** [linux-system-roles/ssh#49]
If I want to use an option not specified in `ssh_config.j2`, am I able to do so? We use a set of options in our ssh_config, some of which aren't included in the template, and I'd like to know whether we can still use this supported role.

Is there a reason why the available options are specified explicitly, rather than just looping through a list of options?

Thanks

**Comment by Jakuje** [comment]
This role is based on the sshd role with similar concepts and in the older versions of OpenSSH, having an unknown option in the configuration prevented the server from starting, which is a huge issue in case of remotely managed server over ssh.

For the client configuration, this should not be that problematic. Right now, it is easy to add new options into https://github.com/linux-system-roles/ssh/blob/master/.dev-tools/options_body and generate new templates.

I dont see a reason why the looping through the list of options would not work right now (as long as both the defaults and user-provided options are consulted) so if you want to draft a pull request, contributions are welcomed.
